### ISSUE TITLE
The plugin puts '& ' in front of the doctest command

### ISSUE THREAD

**Issue by vbrozik** [NoahSyn10/VSCode-PyDoctestBtn#3]
A while ago I installed the extension but I noticed that the command injected into the terminal is invalid.
In addition to the valid command it contains the string `& ` at the beginning.

Example:
`& /usr/bin/python3.9 -m doctest -v /home/vbrozik/programming/check-point-policy-importer/src/cp_importer/json_import.py`

Instead of working:
`/usr/bin/python3.9 -m doctest -v /home/vbrozik/programming/check-point-policy-importer/src/cp_importer/json_import.py`

**Comment by NoahSyn10** [comment]
I implemented it this way to mimic the way the Python extension injects the run command into the terminal, which uses the & symbol. It is possible that that version of the command is Windows PowerShell specific. When I have time again I will likely remove the symbol as I don't think it is necessary even for PowerShell.

What system are you using? Thanks for your feedback!

**Comment by NoahSyn10** [comment]
I removed the & symbol and it still functions fine in PowerShell, hopefully this will fix any issues on other platforms. I will try to get it released as a hotfix soon.

**Comment by vbrozik** [comment]
Thank you an excuse my delayed reply. The extension now works correctly.

I am using Ubuntu 20.04 inside WSL2 and VS Code connects from Windows using Remote-WSL.

I had no idea that in this context `&` is a special operator of PowerShell. (what a weird shell!) Certainly in the usual Unix shells this syntax is invalid. If it is needed `&` should be injected only if the destination shell is PowerShell.

**Comment by NoahSyn10** [comment]
No problem! It definitely seems unique. The command works fine in PowerShell without the '&' so I will simply leave it out for now. I guess it is an operator that allows you to run commands that would not be valid otherwise. https://ss64.com/ps/call.html
