### ISSUE TITLE
Extension doesnt seem to be able to find python

### ISSUE THREAD

**Issue by jguerra-astro** [NoahSyn10/VSCode-PyDoctestBtn#7]
Hello, 
I'm having an issue using this extension. When i currently try to run the doctest using the extension button, a terminal pops up with the following command:
> undefined -m doctest -v "test.py"

when i manually run
> python -m doctest -v "test.py"

this works. 

I looked at the source code and found that the issue is that pyDoctestBtn is trying to find python.pythonPath which after looking around online for a while has been deprecated. 

I can manually add it back, but this doesnt quite work since I would ideally want the python command to be run using the current conda enviroment i am using.

Apologies if this is something that has already been fixed, but i just wanted to point it out since i'd like to keep using this extension!

**Comment by Paul-Durrant** [comment]
It seems that vscode no longer defines the preference that DocTestBTN uses to get to python.

You can get it working again by adding

    "python.pythonPath": "$VIRTUAL_ENV/bin/python"

to your workspace settings. Adjusting the path appropriately if you're not working in a virtual environment.

**Comment by NoahSyn10** [comment]
Looking at the Python Extensions current workspace settings it appears that they changed the setting ID to 'python.defaultInterpreterPath'. I should be able to go in and fix that, but Paul's temporary workaround should do the trick in the meantime.

**Comment by NoahSyn10** [comment]
For now I used some code from vscode-code-runner to attempt to retrieve the python path from a location other than python.pythonPath, and I added a fallback setting to the extension that you can edit to be your python path if the extension cannot find one. If anyone understands how to extract the appropriate python path automatically now that python.pythonPath is depreciated, I am trying to figure it out.
